### ISSUE TITLE
打包出现缺少index.html

### ISSUE THREAD

**Issue by zhanshengxiaoyu** [TangSengDaoDao/TangSengDaoDaoManager#1]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoManager/assets/92144287/ec3aba04-7630-40e4-b71a-e217885587a0)

如图 是什么情况

**Comment by zhanshengxiaoyu** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoManager/assets/92144287/63141117-eafa-48af-8f2f-05ec95e37e2f)

本地预览就可以正常

**Comment by budou0608** [comment]
node版本是多少

**Comment by budou0608** [comment]
<img width="1088" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoManager/assets/22893139/83f7a02e-a352-446d-afd4-220988e80cea">
node版本：v16.16.0 试一下

1. node版：

**Comment by budou0608** [comment]
问题找到了vite-plugin-html-template在windows，电脑不兼容问题

**Comment by zhanshengxiaoyu** [comment]
node版本  16.20.1  Windows 11环境

**Comment by budou0608** [comment]
已修复换vite-plugin-html插件
