### ISSUE TITLE
本地 怎么登录啊 ？

### ISSUE THREAD

**Issue by JasonZ023** [TangSengDaoDao/TangSengDaoDaoManager#4]

**Comment by zaclau-dev** [comment]
开源开一半出来 ？

**Comment by tangtaoit** [comment]
> 开源开一半出来 ？

这个仅仅是后台管理前端，你需要部署后台服务才能登录，后台服务也是开源的：https://github.com/TangSengDaoDao/TangSengDaoDaoServer
