### ISSUE TITLE
默认账号密码是什么？

### ISSUE THREAD

**Issue by zoujiaqing** [TangSengDaoDao/TangSengDaoDaoManager#5]
docker 部署了管理界面，默认账号密码是什么呢？

**Comment by tangtaoit** [comment]
部署的时候自己配置的 看文档

**Comment by tangtaoit** [comment]
部署的时候自己设置的 看文档：

<img width="787" alt="image" src="https://github.com/user-attachments/assets/2dd48033-014f-4ce4-9941-efb86a204926">
